data:
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed

templates:
  raw: "{quarter}.csv"   # Raw input files (e.g. data/raw/2024Q4.csv)
  interim: "credit_risk_raw_{quarter}.csv" # Intermediate, cleaned CSV (e.g. data/interim/credit_risk_raw_2024Q4.csv)
  processed: "credit_risk_features_{quarter}.csv"   # Processed‐features CSV (e.g. data/processed/credit_risk_features_2024Q4.csv)

features:
  target: "default_flag"
  sensitive:
    - "property_state"

model:
  random_seed: 42

  # Base XGBoost settings
  xgboost:
    n_estimators:   400
    max_depth:      4
    learning_rate:  0.2

  # base lightgbm settings
  lightgbm:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1

  # Data‐balance / class‐weighting
  resample:          smote         # or: none
  use_class_weight:  true          # scale_pos_weight if not using resample

  # What metric to optimize in GridSearchCV
  optimize_for:      recall        # or: average_precision

  # Hyperparameter tuning grid
  tuning:
    cv_folds: 5
    grid:
      n_estimators:   [50, 100, 200, 400]
      max_depth:      [4, 6, 8, 10]
      learning_rate:  [0.05, 0.1, 0.2]

  # Probability calibration
  do_calibration:     true
  calibration_method: isotonic     # or: sigmoid

  # Threshold‐selection settings
  threshold:
    pct_grid:      [0.01, 0.02, 0.05, 0.10, 0.15]
    precision_min: 0.04            # require at least 4% precision
    pct_max:       0.05            # never flag more than 5% of loans
    top_pct:       0.05            # final fixed slice (5%)

  # Where to write the serialized model + threshold
  output_dir: models
  output_template: final_model_{quarter}.joblib

  fairlearn:
    method: reduction              # “reduction” (in‑training) or “postprocessing”
    constraint: demographic_parity     # or “equalized_odds”
    epsilon: 0.02                   # allowable gap (e.g. 2pp)
    sensitive_feature: property_state          # column name in your feature set
  selection:
    rule: constraint        # or "utility"
    min_accuracy: 0.94
    max_gap: 0.04
    lambda: 0.5

  prediction_dir: predictions
